/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.ciudadDTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.ICiudadNegocio;
import negocio.NegocioException;
import persistencia.ICiudadDAO;
import persistencia.IClienteDAO;

/**
 *
 * @author santi
 */
public class frmFuncion extends javax.swing.JFrame {

    IClienteDAO cliente = this.cliente;
    ICiudadNegocio ciudad = this.ciudad;
    /**
     * Creates new form frmLogin
     */
    public frmFuncion(ICiudadNegocio ciudadNegocio) {
        this.ciudad = ciudadNegocio;
        initComponents();
        llenarBoxCiudades(buscarCiudadTabla());
    }
    
    private List<ciudadDTO> buscarCiudadTabla() {
        List<ciudadDTO> ciudadLista = null;
        try {
            
            ciudadLista = this.ciudad.buscarCiudadTabla();


        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Información", JOptionPane.ERROR_MESSAGE);
        }

        return ciudadLista;
    }  
    
    private void llenarBoxCiudades(List<ciudadDTO> ciudadLista) {
        int i = 0;
        while (ciudadLista.size() > i) {
            boxCiudad.addItem(ciudadLista.get(i).getNombre());
            i++;
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        boxCiudad = new javax.swing.JComboBox<>();
        boxSucursal = new javax.swing.JComboBox<>();
        btnACiudad = new javax.swing.JButton();
        btnASucursal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncion = new javax.swing.JTable();
        btnFuncion = new javax.swing.JButton();
        btnSucursal = new javax.swing.JButton();
        btnPeliculas = new javax.swing.JButton();
        btnSalas = new javax.swing.JButton();
        jLLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 456, -1, -1));

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 456, -1, -1));

        boxCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(boxCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 160, -1, -1));

        boxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(boxSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 160, -1, -1));

        btnACiudad.setText("Aceptar");
        getContentPane().add(btnACiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 160, -1, -1));

        btnASucursal.setText("Aceptar");
        getContentPane().add(btnASucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 160, -1, -1));

        tblFuncion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFuncion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 199, 678, 214));

        btnFuncion.setText("Agregar Funcion");
        getContentPane().add(btnFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 160, -1, -1));

        btnSucursal.setText("Agregar Sucursal");
        getContentPane().add(btnSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 199, -1, -1));

        btnPeliculas.setText("Agregar Películas");
        getContentPane().add(btnPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 238, -1, -1));

        btnSalas.setText("Agregar Salas");
        getContentPane().add(btnSalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 277, 125, -1));

        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/Cinépolis (1).png"))); // NOI18N
        getContentPane().add(jLLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 450, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        IClienteDAO cliente = this.cliente;        
        ICiudadNegocio ciudad = this.ciudad;
        frmLogin x = new frmLogin(cliente, ciudad);
        x.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        frmBoletos x = new frmBoletos();
        x.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void boxCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxCiudadActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCiudad;
    private javax.swing.JComboBox<String> boxSucursal;
    private javax.swing.JButton btnACiudad;
    private javax.swing.JButton btnASucursal;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnFuncion;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPeliculas;
    private javax.swing.JButton btnSalas;
    private javax.swing.JButton btnSucursal;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFuncion;
    // End of variables declaration//GEN-END:variables
}
