/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.validarClienteDTO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.ICiudadNegocio;
import persistencia.ClienteDAO;
import persistencia.ICiudadDAO;
import persistencia.IClienteDAO;
import persistencia.PersistenciaException;

/**
 *
 * @author santi
 */
public class frmIniciarSesion extends javax.swing.JFrame {

    IClienteDAO cliente = this.cliente;    
    ICiudadNegocio ciudad = this.ciudad;
    /**
     * Creates new form frmLogin
     */
    public frmIniciarSesion(IClienteDAO cliente, ICiudadNegocio ciudad) {
        this.cliente = cliente;
        this.ciudad = ciudad;
        initComponents();
    }

        
    private boolean validarCliente(validarClienteDTO cliente) throws PersistenciaException{

    return this.cliente.validarCliente(cliente);

    }                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fldCorreo = new javax.swing.JTextField();
        fldContraseña = new javax.swing.JTextField();
        jLLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 279, -1, -1));

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 279, -1, -1));

        jLabel4.setText("Correo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 169, 127, -1));

        jLabel5.setText("Contraseña");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 213, 178, -1));
        getContentPane().add(fldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 164, 181, -1));
        getContentPane().add(fldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 208, 181, -1));

        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/Cinépolis (1).png"))); // NOI18N
        getContentPane().add(jLLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 400, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        IClienteDAO cliente = this.cliente;
        ICiudadNegocio ciudad = this.ciudad;
        frmLogin x = new frmLogin(cliente, ciudad);
        x.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        ICiudadNegocio ciudad = this.ciudad;
        String val1 = fldCorreo.getText();
        String val2 = fldContraseña.getText(); 
        validarClienteDTO clienteAV = new validarClienteDTO(val1, val2);        
        try {
            if (validarCliente(clienteAV) == true){
                
                JOptionPane.showMessageDialog(this, "Sesión Iniciada");
                frmFuncion x = new frmFuncion(ciudad);
                x.setVisible(true);
                setVisible(false);
            } else JOptionPane.showMessageDialog(this, "Datos de inicio de sesión inexistentes");        
        } catch (PersistenciaException ex) {
            Logger.getLogger(frmIniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField fldContraseña;
    private javax.swing.JTextField fldCorreo;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
