/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import negocio.ICiudadNegocio;
import persistencia.ClienteDAO;
import persistencia.ICiudadDAO;
import persistencia.IClienteDAO;

/**
 *
 * @author santi
 */
public class frmLogin extends javax.swing.JFrame {

    private IClienteDAO cliente;
    private ICiudadNegocio ciudad;
    /**
     * Creates new form frmLogin
     */
    public frmLogin(IClienteDAO cliente, ICiudadNegocio ciudad) {
        this.cliente = cliente;
        this.ciudad = ciudad;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarSesión = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciarSesión.setText("Iniciar Sesión");
        btnIniciarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesiónActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilerias/Cinépolis (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 110));

        jLabel2.setText("Registrarte para tener diferentes beneficios en la pagina como poder ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 370, 30));

        jLabel3.setText("comprar boletos en línea, si ya tiene cuenta inicie sesión");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesiónActionPerformed
        // TODO add your handling code here:
        IClienteDAO cliente = this.cliente;
        ICiudadNegocio ciudad = this.ciudad;
        frmIniciarSesion x = new frmIniciarSesion(cliente, ciudad);
        x.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnIniciarSesiónActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        IClienteDAO cliente = this.cliente;
        ICiudadNegocio ciudad = this.ciudad;
        frmRegistro x = new frmRegistro(cliente, ciudad);
        x.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnRegistroActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesión;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
